apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rest-api-db
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rest-api-db
spec:
  source:
    git:
      url: https://github.com/trisberg/rest-api-db
      ref:
        branch: main
